# Turn on ZMK Studio
CONFIG_ZMK_STUDIO=y

# Enable deep sleep to save battery (sleeps after 15 mins)
CONFIG_ZMK_SLEEP=y

# Disable Studio security locking (Crucial for 1-key boards)
CONFIG_ZMK_STUDIO_LOCKING=n

# Force a faster Bluetooth connection for less latency
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
